In [92]:
#Первое задание
import numpy as np
import scipy.io as sio
import scipy.optimize as so

A = np.array([[1, 2,3], [-2,3, 0],[5,1,4]])
B = np.array([[1, 2,3], [-2,4, 6],[3,7,2]])
u = np.array([[-4], [1],[1]])
v = np.array([[3], [2],[10]])



In [93]:
#Второе задание
C = np.random.random((100, 100))
print (C)

[[0.80727099 0.17886674 0.80623575 ... 0.52042178 0.94221723 0.49584461]
 [0.82924858 0.80319921 0.50847286 ... 0.72169414 0.60590534 0.51260631]
 [0.04241549 0.54176421 0.36965193 ... 0.13012997 0.6508014  0.98286157]
 ...
 [0.95954664 0.6455346  0.60319392 ... 0.30056646 0.67612314 0.38912674]
 [0.97727183 0.51609036 0.9149833  ... 0.05559862 0.60742014 0.95481893]
 [0.71419829 0.62936083 0.61327237 ... 0.06954272 0.62852232 0.51315845]]


In [94]:
w = np.random.random((100, 1))


In [95]:
#Третье задание
print(A+B)
print(A*B)
print(A*A*A)
print(A*B*A)

[[ 2  4  6]
 [-4  7  6]
 [ 8  8  6]]
[[ 1  4  9]
 [ 4 12  0]
 [15  7  8]]
[[  1   8  27]
 [ -8  27   0]
 [125   1  64]]
[[ 1  8 27]
 [-8 36  0]
 [75  7 32]]


In [96]:
print(v.T*A.T*(u+2*u))
print(u*v)
print(C*w)
print(w.T*C)

[[ -36   48 -600]
 [  18   18   30]
 [  27    0  120]]
[[-12]
 [  2]
 [ 10]]
[[0.70915591 0.15712742 0.70824649 ... 0.45717013 0.82770089 0.43558004]
 [0.36568536 0.354198   0.2242284  ... 0.31825557 0.26719456 0.22605118]
 [0.03954997 0.50516351 0.34467885 ... 0.1213386  0.60683434 0.91646106]
 ...
 [0.63565005 0.4276333  0.39958479 ... 0.19910974 0.44789663 0.25777635]
 [0.28316836 0.14953921 0.26512001 ... 0.01610992 0.17600238 0.27666254]
 [0.55448299 0.48861763 0.47612701 ... 0.05399097 0.48796664 0.39840145]]
[[0.70915591 0.07887737 0.7517678  ... 0.34475253 0.27301115 0.38495948]
 [0.72846237 0.354198   0.47412127 ... 0.47808506 0.17556346 0.39797278]
 [0.03726034 0.23890935 0.34467885 ... 0.08620438 0.18857227 0.76306542]
 ...
 [0.8429241  0.28467043 0.56244314 ... 0.19910974 0.19590934 0.3021068 ]
 [0.85849498 0.22758759 0.85316854 ... 0.03683121 0.17600238 0.74129393]
 [0.6273952  0.27753806 0.5718407  ... 0.04606846 0.18211682 0.39840145]]


In [97]:
#Четвёртое задание
d = np.random.random((20, 20))
number = 1
for index in range(1,400):  
    number *=index
for i in range(20):
    for j in range(20):
        d[i,j] = i*j

In [98]:
# Пятое задание
sio.savemat ('data.mat', {'A': A, 'B':B, 'v':v,'u':u}) # Указано имя файла, имя матрицы в архиве и сама матрица
C = sio.loadmat('data.mat')['u'] # Загружаем матрицу под именем A и помещаем в переменную B
print (C)



[[-4]
 [ 1]
 [ 1]]


In [99]:
# Шестое задание
a =A[A>0] 
b =B[B>0]
sum =0
for i in b:
    sum +=i
for i in a:
    sum+=i

print (sum+sum)

94


In [100]:
# Седьмое задание
print(A[A>0])

[1 2 3 3 5 1 4]


In [101]:
#Восьмое задание
np.linalg.inv(A)
np.linalg.pinv(A, rcond=1e-15)
np.linalg.inv(B)
np.linalg.pinv(B, rcond=1e-15)


array([[ 5.00000000e-01, -2.50000000e-01, -2.63677968e-16],
       [-3.23529412e-01,  1.02941176e-01,  1.76470588e-01],
       [ 3.82352941e-01,  1.47058824e-02, -1.17647059e-01]])

In [102]:
#Девятое задание
print(np.linalg.eigh(m.A))

NameError: name 'm' is not defined

In [ ]:
#Десятое задание
def f1(x):
    return 5*(x-2)**4 -1/(x**2 +8)
def f2(x1,x2):
    return 4*(x1-3*x2)**2 + 7*x1**4
print (f1(1))
print (f2(1,1))
x_min = so.minimize(f1, 0.0, method='BFGS') # 0.0 — начальная точка
x1_min = so.minimize(f2,0.0,0.0,method ='BFGS')


In [ ]:
#Одинадцатое задание
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import rc
rc('font', family='Verdana')
x = np.linspace(0, 6*np.pi, 100)
y1 = x**5 +2*x**4 -3*x -7
y2 = x**5 -2*x**4 +3*x -7

plt.plot(x, y1, ':r')
plt.plot(x, y2, '-.b')

plt.xlabel('x')
plt.ylabel('y')

plt.legend(['Первый график', 'Второй график']) # Названия в порядке отображения графиков

plt.title('Синус и косинус')
plt.show()


In [103]:
#Двенадцатое задание
# rc('font', family='Verdana')
x = np.linspace(0, 6*np.pi, 100)
y1 = x**5 +2*x**4 -3*x -7
y2 = x**5 -2*x**4 +3*x -7

plt.subplot(2,1,1)
plt.plot(x, y1)
plt.subplot(2,2,2)
plt.plot(x, y2)
plt.xlabel('x')
plt.ylabel('y')

plt.legend(['Первый график', 'Второй график']) # Названия в порядке отображения графиков

plt.title('')

plt.show()

NameError: name 'plt' is not defined

In [ ]:
#13 задание
